# Site settings
title: Beautifurl
email: info@beautifurl.co
url: https://beautifurl.co

# Meta
meta_author: Boris Mann
description: "BEAUTIFURL - make your URLs beautiful when they unfurl or embed in Slack, Medium, Facebook, Twitter, and more."
meta_twitter: beautifurl
meta_facebook: beautifurl
meta_image: "/img/curly256.png"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

skills: ""

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "64BE07"
  primary-rgb: "100,190,7"
  secondary: "3A2306"
  secondary-dark: "2C1806"

# Footer settings
footer:
  copyright: BEAUTIFURL
  location: Location
  social: Around the Web
  credits: About

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/beautifurlco
  - title: facebook
    url: https://www.facebook.com/beautifurl

# Postal address (add as many lines as necessary)
address:
  - line: 1201 - 555 W Hastings
  - line: Vancouver, BC, Canada

# Credits content
credits: 'Beautifurl is a hosted service to help you customize the images and information that displays when other services embed your links.'

# Build settings
markdown: kramdown
permalink: pretty

exclude: [README.md, LICENCE, screenshot.png]
