# Site settings
title: Beautifurl
email: info@beautifurl.co
url: https://beautifurl.co
description: "BEAUTIFURL - make your URLs beautiful when they unfurl or embed in Slack, Medium, and more."
skills: ""
meta_author: Mann Boris

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: BEAUTIFURL
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/beautifurlco
  - title: facebook
    url: https://www.facebook.com/beautifurl

# Postal address (add as many lines as necessary)
address:
  - line: 1201 - 555 W Hastings
  - line: Vancouver, BC, Canada

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

exclude: [README.md, LICENCE, screenshot.png]
